/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */

    public Login() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        addPlaceholderStyle(emailJT);
        addPlaceholderStyle(passJP);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        emailJT = new javax.swing.JTextField();
        passJP = new javax.swing.JPasswordField();
        selectJC = new javax.swing.JComboBox<>();
        signJB = new javax.swing.JButton();
        daftarJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN IN WITH YOUR ACCOUNT");

        emailJT.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        emailJT.setText("Silahkan masukan email");
        emailJT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailJTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailJTFocusLost(evt);
            }
        });

        passJP.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        passJP.setText("Password");
        passJP.setEchoChar('\u0000');
        passJP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passJPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passJPFocusLost(evt);
            }
        });

        selectJC.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        selectJC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih masuk sebagai", "Admin", "Siswa" }));

        signJB.setBackground(new java.awt.Color(0, 204, 204));
        signJB.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        signJB.setForeground(new java.awt.Color(255, 255, 255));
        signJB.setText("SIGN IN!");
        signJB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        signJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signJBActionPerformed(evt);
            }
        });

        daftarJL.setForeground(new java.awt.Color(255, 255, 255));
        daftarJL.setText("Belum memiliki akun? Silahkan daftar disini!");
        daftarJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarJLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(daftarJL))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(selectJC, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passJP)
                                    .addComponent(emailJT, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                                .addComponent(signJB, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(emailJT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(passJP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(selectJC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(signJB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daftarJL))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addPlaceholderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.BLACK);
    }
    
    public void removePlaceholderStyle(JTextField textField) {
        Font font = textField.getFont();
        //font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    private void daftarJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarJLMouseClicked
        // TODO add your handling code here:
        new Register();
        this.dispose();
    }//GEN-LAST:event_daftarJLMouseClicked

    private void signJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signJBActionPerformed
        try {
            // TODO add your handling code here:
            java.sql.Connection conn = (Connection) Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            String sql = "SELECT * FROM data_akun WHERE email='"+emailJT.getText()+"' AND password='" + passJP.getText()+"' AND jenis_user='" + selectJC.getSelectedItem() + "'";
            java.sql.ResultSet res = stm.executeQuery(sql);
            System.out.println(sql);
            if (res.next()) {
                 String name = emailJT.getText().substring(0, emailJT.getText().indexOf("@"));
                if (emailJT.getText().equals(res.getString("email")) && passJP.getText().equals(res.getString("password")) && selectJC.getSelectedItem().equals(res.getString("jenis_user"))) {
                    if (selectJC.getSelectedItem().equals("Admin")) {
                        JOptionPane.showMessageDialog(null, "Login Success Sebagai Admin", "Massage", JOptionPane.INFORMATION_MESSAGE);
                        new HalamanAdmin();
                        this.dispose();
                    } else {
                         JOptionPane.showMessageDialog(null, "Hallo " + name, "Massage", JOptionPane.INFORMATION_MESSAGE);
                        new HalamanSiswa();
                        this.dispose();
                    }  
                }
            } else {
                 JOptionPane.showMessageDialog(null, "Pastikan username dan password yang anda masukan benar", "Login", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage());
        }       
    }//GEN-LAST:event_signJBActionPerformed

    private void emailJTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailJTFocusGained
        // TODO add your handling code here:
        if (emailJT.getText().equals("Silahkan masukan email")) {
            emailJT.setText("");
            emailJT.requestFocus();
            removePlaceholderStyle(emailJT);
        }
    }//GEN-LAST:event_emailJTFocusGained

    private void passJPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passJPFocusGained
        // TODO add your handling code here:
        if (passJP.getText().equals("Password")) {
            passJP.setText("");
            passJP.requestFocus();
            passJP.setEchoChar('*');
            removePlaceholderStyle(passJP);
        }
    }//GEN-LAST:event_passJPFocusGained

    private void emailJTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailJTFocusLost
        // TODO add your handling code here:
        if (emailJT.getText().length() == 0) {
            addPlaceholderStyle(emailJT);
            emailJT.setText("Silahkan masukan email");
        }
    }//GEN-LAST:event_emailJTFocusLost

    private void passJPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passJPFocusLost
        // TODO add your handling code here:
        if (passJP.getText().length() == 0) {
            addPlaceholderStyle(passJP);
            passJP.setText("Password");
             passJP.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passJPFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarJL;
    private javax.swing.JTextField emailJT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passJP;
    private javax.swing.JComboBox<String> selectJC;
    private javax.swing.JButton signJB;
    // End of variables declaration//GEN-END:variables
}
